name:  Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v1
      
      - name: Run make
        run: make

      - name: Run make test
        run: make test

      - name: Run unit tests
        run: ./bin/test
      - name: Run functional tests
        run: |
          cd tests/func
          ./test.sh
