name: Valgrind

on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v1
      
      - name: Run make
        run: make
      - name: Install valgrind
        run: sudo apt-get install valgrind

      - name: Run valgrind 1
        run: valgrind ./bin/main "$(cat tests/func/b2c.b)"

      - name: Run valgrind 2
        run: valgrind ./bin/main "$(cat tests/func/beer.b)"

      - name: Run valgrind 3
        run: valgrind ./bin/main "$(cat tests/func/dquine.b)"

      - name: Run valgrind 4
        run: valgrind ./bin/main "$(cat tests/func/hellow1.b)"

      - name: Run valgrind 5
        run: valgrind ./bin/main "$(cat tests/func/hellow2.b)"

      - name: Run valgrind 6
        run: valgrind ./bin/main "$(cat tests/func/pi.b)"

      - name: Run valgrind 7
        run: valgrind ./bin/main "$(cat tests/func/quine505.b)"

      - name: Run valgrind 8
        run: valgrind ./bin/main "$(cat tests/func/squares.b)"
          
      - name: Run valgrind 9
        run: valgrind ./bin/main "$(cat tests/func/pic.b)"
