name: Valgrind

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v1
      
      - name: Run make
        run: make

      - name: Run valgrind 1
        run: valgrind ./brainfuck "$(cat b2c.b)"

      - name: Run valgrind 2
        run: valgrind ./brainfuck "$(cat beer.b)"

      - name: Run valgrind 3
        run: valgrind ./brainfuck "$(cat dquine.b)"

      - name: Run valgrind 4
        run: valgrind ./brainfuck "$(cat hellow1.b)"

      - name: Run valgrind 5
        run: valgrind ./brainfuck "$(cat hellow2.b)"

      - name: Run valgrind 6
        run: valgrind ./brainfuck "$(cat pi.b)"

      - name: Run valgrind 7
        run: valgrind ./brainfuck "$(cat quine505.b)"

      - name: Run valgrind 8
        run: valgrind ./brainfuck "$(cat squares.b)"
